services:
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - app_network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     PRODUCTION: 1
  #     APP_PORT: 8080
  #     DB_CONNECTION: pgsql
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     SECRET_KEY: ${SECRET_KEY}
  #     GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  #   depends_on:
  #     - psql
  #   ports:
  #     - "${APP_PORT}:8080"
  #   networks:
  #     - app_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   environment:
  #     VITE_API_URL: "http://app:8080"
  #   ports:
  #     - "${APP_PORT_FE}:80"
  #   networks:
  #     - app_network

networks:
  app_network:

volumes:
  psql_volume:
